apiVersion: v1
kind: Service
metadata:
  labels:
    component-identifier: kube-status
  name: kube-status
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    component-identifier: kube-status
  type: LoadBalancer
